config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create]
  resources :articles
  devise_for :users

  post 'reactions',         to: "reactions#user_reaction",           as: "user_reaction"
  get 'my_reactions',        to: "reactions#article_with_reactions", as: "my_reactions"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :reactions, dependent: :destroy
  has_many :comments, dependent: :destroy

  def count_with_kind(arg)
    number = self.reactions.where(kind: arg).count
    return "#{arg} -#{number}"
end

def find_kind_user_relation(user)
    self.reactions.find_by(user_id: user.id).kind
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :kind , acceptance: {
    accept: %w[like dislike],
  }

  def self.kinds
    %w[like dislike]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments
  has_many :reactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
 
    end
    def after_sign_in_path_for(resource)
        articles_path
    end
  
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :redirect_si_user_no_coincide, only: %i[update edit destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comment= Comment.new
    @comments= Comment.where(article_id: @article.id)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:photo, :description, :when_went, :user_id)
    end

    def redirect_si_user_no_coincide
      if current_user.id != @article.user_id
        redirect_to articles_path, notice: "Solo puedes modificar tus propios post"
      end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :redirect_si_user_no_coincide, only: %i[update edit destroy]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @article = Article.find(params[:comment][:article_id])
    @comment = Comment.new(comment_params)
    @comment.user = current_user
   

    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_url(@article), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end
    def redirect_si_user_no_coincide
      if current_user.id != @commeent.user_id
        redirect_to articles_path, notice: "Solo puedes modificar tus propios post"
      end
  end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :article_id, :user_id)
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    before_action :authenticate_user!
    def user_reaction
        @user = current_user
        @article = Article.find(params[:article_id])
        reaction = Reaction.find_by(user_id: @user.id, article_id: @article.id)
            if reaction
                return flash.now[:alert] = 'You already reacted to this post'
            else
                @new_reaction = Reaction.new(user_id: @user.id, article_id: @article.id, kind: params[:kind])
                    respond_to do |format|
                        if @new_reaction.save!
                            format.html { redirect_to article_path(@article), notice: "#{current_user.email} You #{@new_reaction.kind} the Post" }
                        else
                            format.html { redirect_to article_path(@article), status: :unprocessable_entity }
                        end
                    end
            end
        end
        def article_with_reactions
            @articles=Article.all
            @reactions = current_user.reactions
            article_ids = @reactions.map(&:article_id)
            article= Article.where(id:article_ids)
        end

    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Photo:</strong>
    <%= article.photo %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

  <p>
    <strong>When went:</strong>
    <%= article.when_went %>
  </p>

  <p>
    <strong>User:</strong>
    <%= article.user.email %>
  </p>


</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :when_went, style: "display: block" %>
    <%= form.datetime_field :when_went %>
  </div>

  <div>
  
    <%#= form.label :user_id, style: "display: block" %>
    <%#= form.text_field :user_id %>
  </div>
  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/avalaible.html.erb
<h1>Post u liked it!</h1>
<ul>
 <% @articles.each do |article| %>
 <li>
 <%= article.name %> -
 <%= article.reactions.find_by(user_id: current_user.id).kind %>
 <p>
 <%= link_to "Show this post", article %>
 </p>
 </li>
 <% end %>
</ul>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this post", article %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<%if current_user%>
<div>
<%= render 'comments/articlecomments'%>
<%= render 'comments/form' %>
  <%= render "reactions/options"%>
</div>
<% if @article.user_id == current_user.id %>
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Destroy this article", @article, method: :delete %>
  <%= render 'comments/articlecomments'%>
  <%= render 'comments/form' %>
  <%= render "reactions/options"%>
</div>

<%end%>
<%end%>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/comments/_articlecomments.html.erb
<div>
<% @comments.each do |comment| %>
<p>
<div>
<%= comment.content %>
</div>
by <%= comment.user.email%>
</p>
<% end %>
</div>

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>Article:</strong>
    <%= comment.article_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |f| %>
<% if @comment.errors.any? %>
<div id = 'error_explanation'>
<h2>Este comentario no se pudo crear por las siguientes
razones</h2>
<ul>
<% @comment.errors.full_messages.each do |msg|%>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<%= f.hidden_field :article_id, value: @article.id %>
<div class = 'field'>
<%= f.label :content, as: "Contenido" %>
<%= f.text_field :content %>
<div class = 'actions'>
<%= f.submit %>
</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/crazycats/available.html.erb
<h1>Post u liked it!</h1>
<ul>
 <% @articles.each do |article| %>
 <li>
 <%= article.name %> -
 <%= article.reactions.find_by(user_id: current_user.id).kind %>
 <p>
 <%= link_to "Show this post", article %>
 </p>
 </li>
 <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazycats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%=render "shared/navbar"%>
  <div class="container">
 
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reactions/_counters.html.erb
<div>
    <ul>
    <% Reaction.kinds.each do |kind|%>
    <li> <%= @article.count_with_kind(kind)%></li>
    <%end%>
    </ul>
</div>

app/views/reactions/_options.html.erb
<div>
<ul>
<%Reaction.kinds.each do |kind|%>
<li><%= button_to "#{kind}", user_reaction_path(article_id: @article.id, kind: kind), method: :post%>
</li>
<%end%>
</ul>
</div>

app/views/reactions/article_with_reactions.html.erb
<h1>Post u liked it!</h1>
<ul>
 <% @articles.each do |article| %>
 <li>
 <%= article.description %> - <%= article.reactions.find_by(user_id: current_user.id) %>
 </li>
 <p>
 <%= link_to "Show this post", article %>
 </p>
 <% end %>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container">
    <%= link_to "CRAZY 4 CATS", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNavDropdown">
        <ul class="navbar-nav me-auto">
            <li>
                <%= link_to "Cats!", articles_path, class:"nav-link" %>
            </li>
        </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <% if user_signed_in? %>
                    Hola <%= current_user.email %>
                <% else %>
                    Inicia sesión o registrate
                <% end %>
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
                <li><%= link_to "Tus reacciones", my_reactions_path, class:"dropdown-item" %></li>
                <li><%= button_to "Cerrar Sesión", destroy_user_session_path, class:"dropdown-item", method: :delete %></li>
            <% else %>
                <li><%= link_to "Iniciar Sesión", new_user_session_path, class:"dropdown-item" %></li>
                <li><%= link_to "Registro", new_user_registration_path, class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>